apiVersion: v2
name: preprod
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
dependencies:
  - name: wscs
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wscs-deployment"
  - name: wsnodejs
    version: "0.1.0"
    repository: "https://raw.githubusercontent.com/tpayne/kubernetes-examples/main/Helm/wsnodejs-deployment"
